name: Trigger auto deployment for containerapp-wxksp4v46ykli

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerapp-wxksp4v46ykli-AutoDeployTrigger-dcc962be-a74c-4109-9cc9-616b5515926b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.secrets.GITHUB_USERNAME }}
          password: ${{ secrets.secrets.GITHUB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPWXKSP4V46YKLI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerapp-wxksp4v46ykli -g AppService.L200.OSS.Nodejs.3 registry.hub.docker.com --username  ${{ secrets.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_PASSWORD}}
            az containerapp update -n containerapp-wxksp4v46ykli -g AppService.L200.OSS.Nodejs.3 --image mywishdotcf/fnapptest:v1.0.0
