name: Trigger auto deployment for containerapp-wxksp4v46ykli

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerapp-wxksp4v46ykli-AutoDeployTrigger-dcc962be-a74c-4109-9cc9-616b5515926b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
         path: /tmp/.buildx-cache
         key: ${{ runner.os }}-buildx-${{ github.sha }}
         restore-keys: |
           ${{ runner.os }}-buildx-       

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.hub.docker.com/containerapp-wxksp4v46ykli:${{ github.sha }}
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          context: ./
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPWXKSP4V46YKLI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerapp-wxksp4v46ykli -g AppService.L200.OSS.Nodejs.3 --server registry.hub.docker.com --username  ${{ secrets.CONTAINERAPPWXKSP4V46YKLI_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPWXKSP4V46YKLI_REGISTRY_PASSWORD }}
            az containerapp update -n containerapp-wxksp4v46ykli -g AppService.L200.OSS.Nodejs.3 --image registry.hub.docker.com/containerapp-wxksp4v46ykli:${{ github.sha }}
